version: "3.9"


services: 
  db: 
    image: postgres:17-bookworm
    container_name: postgres_db
    environment: 
      POSTGRES_USER: postgres
      POSGRES_PASSWORD: meomeomeo123
      POSTGRES_DB: football_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d football_match"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - app

  #backend  
  backend:
    build: ./backend
    container_name: fastapi_app
    ports: 
      - "8080:8080"
    environment: 
      - DATABASE_URL: postgresql://postgres:meomeomeo123@db:5432/football_db
    depends_on:
      db: 
        condition: service_healthy
    networks: 
      - app 
    
    # dbt
  dbt: 
    build: ./transformation 
    container_name: transformation
    depends_on:
      db: 
        condition: service_healthy
    networks: 
      - app


  network: 
    app: 
      drive: bridge
  
  volumes: 
    postgres_data: 